version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: flask_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: proyectowebflask
      MYSQL_USER: flaskuser
      MYSQL_PASSWORD: flaskpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./Database.sql:/docker-entrypoint-initdb.d/Database.sql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data: